#!/usr/bin/env php
<?php

if (version_compare(PHP_VERSION, '7.0.0', '<')) {
    fwrite(STDERR, "PHP minimum version required is 7.0.0, current is ".PHP_VERSION.PHP_EOL);
    exit(1);
}

require_once __DIR__ . '/vendor/autoload.php';

$application = new Thorr\Advent\Application();
$application->run();
